
O programa lê um vetor de N números inteiros e calcula a média aritmética apenas dos elementos que são pares. Caso não existam números pares no vetor, o programa deve emitir uma mensagem específica (Nenhum número par).

Algoritmo "media_pares"

Var

   vet: vetor[0..99] de inteiro
   quant, N, i, pares, cont: inteiro
   mediapares: real


Inicio

     escreva("Quantos elementos vai ter o vetor? ")
     leia(quant)


  pares <-0
  cont<-0
     para i de 0 ate quant - 1 faca
     
      escreva("Digite um número:")
      leia(N)

      se N % 2 = 0 entao
       pares <- pares + N
       cont<-cont + 1
      fimse

     fimpara

se cont = 0 entao
  escreva("Nenhum número par!")
senao
     mediapares <- pares / cont
  escreval()
  escreval("Média dos pares = ", mediapares:2:1)
fimse
     
Fimalgoritmo
